apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
data:
  # property-like keys; each key maps to a simple value
  MONGO_DB: {mongo_db_path}
  
  # file-like keys
  test.properties: |
    test.val=aliens,monsters
    test.val2=5
  
