# Url Based Routing Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: be-voting-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: srahul3votingbe.centralindia.cloudapp.azure.com
    http:
      paths:
      - path: /voting
        backend:
          serviceName: node-voting-be-svc
          servicePort: 8080
      - path: /vote/(.+)
        backend:
          serviceName: node-voting-be-svc
          servicePort: 8080